apiVersion: v1
kind: Service
metadata:
  labels:
    service: udgram-reverseproxy
  name: udgram-reverseproxy-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udgram-reverseproxy